//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjectAli.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Chef
    {
        public int ChefID { get; set; }


        public string ChefName { get; set; }


        public string EmailAddress { get; set; }


        public string CellPhone { get; set; }


        public string ContactAddress { get; set; }
    }
}
