//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjectAli.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MvcProjectAliEntities : DbContext
    {
        public MvcProjectAliEntities()
            : base("name=MvcProjectAliEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Tourist> Tourists { get; set; }
        public virtual DbSet<Chef> Chefs { get; set; }
        public virtual DbSet<Guide> Guides { get; set; }
        public virtual DbSet<Reporter> Reporters { get; set; }
    }
}
