//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcProjectAli.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hotel
    {
        public int HotelID { get; set; }
        [Display(Name = "Hotel Name")]
        [Required(ErrorMessage = "Please input hotel name here!!!")]
        [StringLength(30, MinimumLength = 3, ErrorMessage = "Name must be 3-30 character")]
        public string HotelName { get; set; }
        public Nullable<int> TouristId { get; set; }

        [Display(Name = "Joining Date")]
        [Required(ErrorMessage = "Please input your Joining date here!!!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public System.DateTime JoinDate { get; set; }

        [Display(Name = "Release Date")]
        [Required(ErrorMessage = "Please input your release date here!!!")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}")]
        public System.DateTime ReleaseDate { get; set; }

        [Display(Name = "Room Charge")]
        [Required(ErrorMessage = "Please input your room charge here!!!")]
        [Range(99, 99999, ErrorMessage = "Charge must be 99 to 99999 tk.")]
        public int RoomCharge { get; set; }

        [Display(Name = "Service Charge")]
        [Required(ErrorMessage = "Please input your service charge here!!!")]
        [Range(99, 99999, ErrorMessage = "Charge must be 99 to 99999 tk.")]
        public int ServiceCharge { get; set; }

        [Display(Name = "Food Cost")]
        [Required(ErrorMessage = "Please input your food cost here!!!")]
        [Range(99, 99999, ErrorMessage = "Charge must be 99 to 99999 tk.")]
        public int FoodCost { get; set; }
        public Nullable<int> Total { get; set; }

        public virtual Tourist Tourist { get; set; }
    }
}
